/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlliancesRouteImport } from './routes/alliances'
import { Route as ChannelProgramsRouteImport } from './routes/channel-programs'
import { Route as SoteriaRouteImport } from './routes/soteria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlliancesRoute = AlliancesRouteImport.update({
  id: '/alliances',
  path: '/alliances',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelProgramsRoute = ChannelProgramsRouteImport.update({
  id: '/channel-programs',
  path: '/channel-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const SoteriaRoute = SoteriaRouteImport.update({
  id: '/soteria',
  path: '/soteria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alliances': typeof AlliancesRoute
  '/channel-programs': typeof ChannelProgramsRoute
  '/soteria': typeof SoteriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alliances': typeof AlliancesRoute
  '/channel-programs': typeof ChannelProgramsRoute
  '/soteria': typeof SoteriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alliances': typeof AlliancesRoute
  '/channel-programs': typeof ChannelProgramsRoute
  '/soteria': typeof SoteriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alliances' | '/channel-programs' | '/soteria'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alliances' | '/channel-programs' | '/soteria'
  id: '__root__' | '/' | '/alliances' | '/channel-programs' | '/soteria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlliancesRoute: typeof AlliancesRoute
  ChannelProgramsRoute: typeof ChannelProgramsRoute
  SoteriaRoute: typeof SoteriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alliances': {
      id: '/alliances'
      path: '/alliances'
      fullPath: '/alliances'
      preLoaderRoute: typeof AlliancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-programs': {
      id: '/channel-programs'
      path: '/channel-programs'
      fullPath: '/channel-programs'
      preLoaderRoute: typeof ChannelProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soteria': {
      id: '/soteria'
      path: '/soteria'
      fullPath: '/soteria'
      preLoaderRoute: typeof SoteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlliancesRoute: AlliancesRoute,
  ChannelProgramsRoute: ChannelProgramsRoute,
  SoteriaRoute: SoteriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
